version: "3.8"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: currency-conversion-client
        ports:
            - 5173:5173
        depends_on:
            - server
        networks:
            - client-network

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: currency-conversion-server
        depends_on:
            - redis
        ports:
            - 5000:5000
        networks:
            - client-network
            - server-network

    redis:
        image: redis:alpine
        container_name: currency-conversion-redis
        networks:
            - server-network

networks:
    client-network:
        name: currency-conversion-client-network
    server-network:
        name: currency-conversion-server-network
