version: "3.8"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: currency-conversion-client
        ports:
            - 5173:5173
        depends_on:
            - server

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: currency-conversion-server
        ports:
            - 5000:5000
